### ISSUE TITLE
Add support for extended length APDUs

### ISSUE THREAD

**Issue by mistial-dev** [wsct/WSCT-Core#4]
At present, APDUs greater than a single byte are not supported:

https://github.com/wsct/WSCT-Core/blob/4af3decc6173df16d2001b61c7fbe5553fb34970/WSCT/ISO7816/CommandAPDU.cs#L15

I'm going to be adding support here for longer APDUs, and am filing an issue here to reference in commits and pull requests.

**Comment by wsct** [comment]
I should have handled Lc and Le coded on multiple bytes from the beginning of the project, but I didn't for historical reasons.
May I suggest the introduction of Nc and Ne properties along the existing Lc and Le ? (Lc codes Nc, Le codes Ne, as defined by the ISO/IEC 7816).
I'll be happy to study any merge request that tries to fix this without impacting the other existing plugins and projects.

**Comment by mistial-dev** [comment]
> I should have handled Lc and Le coded on multiple bytes from the beginning of the project, but I didn't for historical reasons. May I suggest the introduction of Nc and Ne properties along the existing Lc and Le ? (Lc codes Nc, Le codes Ne, as defined by the ISO/IEC 7816). I'll be happy to study any merge request that tries to fix this without impacting the other existing plugins and projects.

Ok.

I'm interested in maintaining compatibility as well.  I'm on ARM mac, and there are issues with PCSC.Net on this platform.  I'm switching the code I have that uses it over to WSCT-Core, because it "just works".  Most of it uses standard length APDUs, but some of it uses extended.

I'll implement Nc and Ne to keep consistency with the standard.

**Comment by mistial-dev** [comment]
@wsct Is this the kind of thing you were thinking of?

https://github.com/mistial-dev/WSCT-Core/commit/d95e9ce5a269e3b4f29622f2acbaedaffab63e0b

There is still some work to do, just wanted to make sure I wasn't going to cause conflicts or problems.

**Comment by wsct** [comment]
It looks good to me, you successfully grabbed what I was thinking.
The introduction of Nc and Ne should allow existing plugins/app working with short CCx to still do their work, while allowing extended CC to be supported by new or updated plugins.

**Comment by mistial-dev** [comment]
Sounds good.  I'll add a bit more testing and exceptions out, then get it out as a Pull Request.

**Comment by mistial-dev** [comment]
@wsct XML backwards compatibility requires a minor change.  Obviously, if there's a length more than 255, it can be inferred that it must be extended length.  When having XML like this, though:

```
<commandAPDU cla=... ins=... p1=... p2=... (le=...) > udc </commandAPDU>
```

I can't necessarily tell if it's extended or regular length without doing a multi-byte length encoding.  I can do Le=XXXX for example (even for a value < 256), but it gets interesting when Le is missing, and UDC is less than 256 bytes.

There's no way to encode that "I want an extended APDU, no Le, a couple bytes of UDC" with the current XML setup.

**Comment by mistial-dev** [comment]
Spent a bit of time working on the XML serialization, and was able to keep it backwards-compatible and maintain the same XML for non-extended command APDUs.

It was necessary to add an extended attribute, but that will not interfere with existing serialized XML.

https://github.com/mistial-dev/WSCT-Core/commit/1fc2e7a48ac6b7f60f7526741a4f0ceeb68ffdaf

I also implemented equality checking to help with the testing.

**Comment by wsct** [comment]
WSCT.Core package updated to 6.3.0 on nuget and github packages.
Thank you!
